version: 2

sphinx:
  builder: html
  configuration: doc/source/conf.py

python:
  version: 3.8
  system_packages: true
  install:
    - method: pip
      path: .

# Don't build any extra formats
formats: []
