language: c

os:
    - linux
    #- osx

sudo: false

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/conda-dev'
        - CONDA_DEPENDENCIES='pytest drizzlepac'
        - PIP_DEPENDENCIES=""

    matrix:
        - PYTHON_VERSION=3.5 SETUP_CMD='install'
        - PYTHON_VERSION=3.5 SETUP_CMD='test'
        - PYTHON_VERSION=3.6 SETUP_CMD='install'
        - PYTHON_VERSION=3.6 SETUP_CMD='test'
matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # Do a PEP8 test with pycodestyle
        - python: 3.5
          env: MAIN_CMD='pycodestyle stwcs --count' SETUP_CMD=''

        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx'
               PIP_DEPENDENCIES='sphinx-automodapi'

    allow_failures:
        # Do a PEP8 test with pycodestyle
        - python: 3.5
          env: MAIN_CMD='pycodestyle stwcs --count' SETUP_CMD=''

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD
