language: c

os:
    - linux
    - osx

sudo: false

env:
    # CONDA_JWST_DEPENDENCIES is used because CONDA_DEPENDENCIES is not truly global.
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/conda-dev'
        - CONDA_DEPENDENCIES='pytest jwst sphinx=1.3.5'
        - CONDA_JWST_DEPENDENCIES='pytest stsci-jwst sphinx=1.3.5'
        - PIP_DEPENDENCIES=""

    matrix:
        - PYTHON_VERSION=2.7 SETUP_CMD='install'
        - PYTHON_VERSION=2.7 SETUP_CMD='test'
        - PYTHON_VERSION=3.5 SETUP_CMD='install'
        - PYTHON_VERSION=3.5 SETUP_CMD='test'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

